name: domain
description: "Core Domain Layer for Gym and Training App."
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: '^3.11.4'

dependencies:
  meta: ^1.11.0
  equatable: ^2.0.5

dev_dependencies:
  test: ^1.24.0
